################################################################################
# 自动生成的文件。不要编辑！
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc_ex.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_comp.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_comp_ex.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_crc.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_crc_ex.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cryp.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cryp_ex.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dac.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dac_ex.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_firewall.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2s.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_irda.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lcd.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pcd.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pcd_ex.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rng.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc_ex.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_smartcard.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_smartcard_ex.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_smbus.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_spi.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim_ex.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tsc.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_usart.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_wwdg.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_adc.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_comp.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_crc.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_crs.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_dac.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_dma.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_exti.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_gpio.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_i2c.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_lptim.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_lpuart.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_pwr.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_rcc.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_rng.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_rtc.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_spi.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_tim.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_usart.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_usb.c \
../libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_utils.c 

OBJS += \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc_ex.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_comp.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_comp_ex.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_crc.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_crc_ex.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cryp.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cryp_ex.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dac.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dac_ex.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_firewall.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2s.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_irda.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lcd.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pcd.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pcd_ex.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rng.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc_ex.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_smartcard.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_smartcard_ex.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_smbus.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_spi.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim_ex.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tsc.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_usart.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_wwdg.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_adc.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_comp.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_crc.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_crs.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_dac.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_dma.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_exti.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_gpio.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_i2c.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_lptim.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_lpuart.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_pwr.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_rcc.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_rng.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_rtc.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_spi.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_tim.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_usart.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_usb.o \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_utils.o 

C_DEPS += \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc_ex.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_comp.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_comp_ex.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_crc.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_crc_ex.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cryp.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cryp_ex.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dac.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dac_ex.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_firewall.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2s.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_irda.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lcd.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pcd.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pcd_ex.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rng.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc_ex.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_smartcard.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_smartcard_ex.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_smbus.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_spi.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim_ex.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tsc.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_usart.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_wwdg.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_adc.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_comp.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_crc.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_crs.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_dac.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_dma.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_exti.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_gpio.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_i2c.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_lptim.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_lpuart.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_pwr.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_rcc.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_rng.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_rtc.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_spi.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_tim.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_usart.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_usb.d \
./libraries/STM32L0xx_HAL_Driver/Src/stm32l0xx_ll_utils.d 


# Each subdirectory must supply rules for building sources it contributes
libraries/STM32L0xx_HAL_Driver/Src/%.o: ../libraries/STM32L0xx_HAL_Driver/Src/%.c
	arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Os -ffunction-sections -fdata-sections -flto -Wall  -g -gdwarf-2 -DSOC_FAMILY_STM32 -DUPP_CG3_PROTOCOL_EN -DUPP_NCG_PROTOCOL_EN -DNDEBUG -DSOC_SERIES_STM32L0 -DUSE_HAL_DRIVER -DSTM32L071xx -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\applications\upp_protocol\inc" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\applications\flash_meter_db\inc" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\applications\flash_history_db\inc" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\applications\module_driver" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\applications\flash_history_db\inc" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\applications\dlp_protocol\inc" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\drivers" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\applications\inc" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\drivers\include" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\drivers\include\config" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\libraries\CMSIS\Device\ST\STM32L0xx\Include" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\libraries\CMSIS\Include" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\libraries\CMSIS\RTOS\Template" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\libraries\STM32L0xx_HAL_Driver\Inc" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\libraries\STM32L0xx_HAL_Driver\Inc\Legacy" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\drivers\port" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\applications" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\cubemx\Inc" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\cubemx" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\packages\FlashDB-v1.0.0\inc" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\packages\fal-v0.5.0\inc" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\rt-thread\components\drivers\include" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\rt-thread\components\drivers\spi\sfud\inc" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\rt-thread\components\drivers\spi" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\rt-thread\components\libc\compilers\minilibc" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\rt-thread\components\utilities\ulog" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\rt-thread\include" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\rt-thread\libcpu\arm\common" -I"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\rt-thread\libcpu\arm\cortex-m0" -include"D:\RT-ThreadStudio\workspace\NWM-J140-MNH-1_Ver73_update5\rtconfig_preinc.h" -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"

